#
# Autogenerated by Thrift Compiler (0.22.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'shared_types'


module Operation
  ADD = 1
  SUBTRACT = 2
  MULTIPLY = 3
  DIVIDE = 4
  VALUE_MAP = {1 => "ADD", 2 => "SUBTRACT", 3 => "MULTIPLY", 4 => "DIVIDE"}
  VALID_VALUES = Set.new([ADD, SUBTRACT, MULTIPLY, DIVIDE]).freeze
end

class Work; end

class AllTypeValues; end

class InvalidOperation < ::Thrift::Exception; end

# Structs are the basic complex data structures. They are comprised of fields
# which each have an integer identifier, a type, a symbolic name, and an
# optional default value.
# 
# Fields can be declared "optional", which ensures they will not be included
# in the serialized output if they aren't set.  Note that this requires some
# manual management in some languages.
class Work
  include ::Thrift::Struct, ::Thrift::Struct_Union
  NUM1 = 1
  NUM2 = 2
  OP = 3
  COMMENT = 4

  FIELDS = {
    NUM1 => {:type => ::Thrift::Types::I32, :name => 'num1', :default => 0},
    NUM2 => {:type => ::Thrift::Types::I32, :name => 'num2'},
    OP => {:type => ::Thrift::Types::I32, :name => 'op', :enum_class => ::Operation},
    COMMENT => {:type => ::Thrift::Types::STRING, :name => 'comment', :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
    unless @op.nil? || ::Operation::VALID_VALUES.include?(@op)
      raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Invalid value of field op!')
    end
  end

  ::Thrift::Struct.generate_accessors self
end

# Exercises all commonly used Thrift wire types in one payload.
# (UUID intentionally omitted for now; requires a newer compiler/runtime path.)
class AllTypeValues
  include ::Thrift::Struct, ::Thrift::Struct_Union
  BOOL_VALUE = 1
  BYTE_VALUE = 2
  I16_VALUE = 3
  I32_VALUE = 4
  I64_VALUE = 5
  DOUBLE_VALUE = 6
  STRING_VALUE = 7
  BINARY_VALUE = 8
  LIST_VALUE = 9
  SET_VALUE = 10
  MAP_VALUE = 11
  STRUCT_VALUE = 12
  STRUCT_LIST_VALUE = 13
  STRUCT_MAP_VALUE = 14
  TYPEDEF_VALUE = 15
  ENUM_VALUE = 16
  OPTIONAL_TEXT = 17

  FIELDS = {
    BOOL_VALUE => {:type => ::Thrift::Types::BOOL, :name => 'bool_value'},
    BYTE_VALUE => {:type => ::Thrift::Types::BYTE, :name => 'byte_value'},
    I16_VALUE => {:type => ::Thrift::Types::I16, :name => 'i16_value'},
    I32_VALUE => {:type => ::Thrift::Types::I32, :name => 'i32_value'},
    I64_VALUE => {:type => ::Thrift::Types::I64, :name => 'i64_value'},
    DOUBLE_VALUE => {:type => ::Thrift::Types::DOUBLE, :name => 'double_value'},
    STRING_VALUE => {:type => ::Thrift::Types::STRING, :name => 'string_value'},
    BINARY_VALUE => {:type => ::Thrift::Types::STRING, :name => 'binary_value', :binary => true},
    LIST_VALUE => {:type => ::Thrift::Types::LIST, :name => 'list_value', :element => {:type => ::Thrift::Types::I32}},
    SET_VALUE => {:type => ::Thrift::Types::SET, :name => 'set_value', :element => {:type => ::Thrift::Types::STRING}},
    MAP_VALUE => {:type => ::Thrift::Types::MAP, :name => 'map_value', :key => {:type => ::Thrift::Types::STRING}, :value => {:type => ::Thrift::Types::I64}},
    STRUCT_VALUE => {:type => ::Thrift::Types::STRUCT, :name => 'struct_value', :class => ::SharedStruct},
    STRUCT_LIST_VALUE => {:type => ::Thrift::Types::LIST, :name => 'struct_list_value', :element => {:type => ::Thrift::Types::STRUCT, :class => ::SharedStruct}},
    STRUCT_MAP_VALUE => {:type => ::Thrift::Types::MAP, :name => 'struct_map_value', :key => {:type => ::Thrift::Types::I32}, :value => {:type => ::Thrift::Types::STRUCT, :class => ::SharedStruct}},
    TYPEDEF_VALUE => {:type => ::Thrift::Types::I32, :name => 'typedef_value'},
    ENUM_VALUE => {:type => ::Thrift::Types::I32, :name => 'enum_value', :enum_class => ::Operation},
    OPTIONAL_TEXT => {:type => ::Thrift::Types::STRING, :name => 'optional_text', :optional => true}
  }

  def struct_fields; FIELDS; end

  def validate
    unless @enum_value.nil? || ::Operation::VALID_VALUES.include?(@enum_value)
      raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Invalid value of field enum_value!')
    end
  end

  ::Thrift::Struct.generate_accessors self
end

# Structs can also be exceptions, if they are nasty.
class InvalidOperation < ::Thrift::Exception
  include ::Thrift::Struct, ::Thrift::Struct_Union
  WHATOP = 1
  WHY = 2

  FIELDS = {
    WHATOP => {:type => ::Thrift::Types::I32, :name => 'whatOp'},
    WHY => {:type => ::Thrift::Types::STRING, :name => 'why'}
  }

  def struct_fields; FIELDS; end

  def validate
  end

  ::Thrift::Struct.generate_accessors self
end

